version: "3.8"

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  server:
    build: ./server
    image: ${DOCKER_HUB_USERNAME}/mern-curd_server:latest  
    ports:
      - "8082:8082"
    depends_on:
      - mongo
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  client:
    build: ./client
    image: ${DOCKER_HUB_USERNAME}/mern-curd_client:latest  
    ports:
      - "3000:3000"
    depends_on:
      - server
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
