version: "3.8"

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  server:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server

